// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets(sha256,object_key,mime_type,byte_size,width,height,created_by,created_at)
VALUES (?,?,?,?,?,?,?,?) RETURNING id, sha256, object_key, mime_type, byte_size, width, height, created_by, created_at, deleted_at
`

type CreateAssetParams struct {
	Sha256    string
	ObjectKey string
	MimeType  string
	ByteSize  int64
	Width     int64
	Height    int64
	CreatedBy int64
	CreatedAt int64
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.Sha256,
		arg.ObjectKey,
		arg.MimeType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, sha256, object_key, mime_type, byte_size, width, height, created_by, created_at, deleted_at FROM assets WHERE id = ?
`

func (q *Queries) GetAsset(ctx context.Context, id int64) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetByHash = `-- name: GetAssetByHash :one
SELECT id, sha256, object_key, mime_type, byte_size, width, height, created_by, created_at, deleted_at FROM assets WHERE sha256 = ?
`

func (q *Queries) GetAssetByHash(ctx context.Context, sha256 string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByHash, sha256)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetsByIDs = `-- name: GetAssetsByIDs :many
SELECT id, sha256, object_key, mime_type, byte_size, width, height, created_by, created_at, deleted_at FROM assets WHERE id IN (/*SLICE:ids*/?) ORDER BY id
`

func (q *Queries) GetAssetsByIDs(ctx context.Context, ids []int64) ([]Asset, error) {
	query := getAssetsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.ObjectKey,
			&i.MimeType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT id, sha256, object_key, mime_type, byte_size, width, height, created_by, created_at, deleted_at FROM assets WHERE id > ?1
AND (deleted_at IS NULL OR ?2) ORDER BY id LIMIT ?3
`

type ListAssetsParams struct {
	AfterID        int64
	IncludeDeleted interface{}
	PageSize       int64
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, arg.AfterID, arg.IncludeDeleted, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.ObjectKey,
			&i.MimeType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAssetDeleted = `-- name: SetAssetDeleted :one
UPDATE assets SET deleted_at = ? WHERE id = ? RETURNING id, sha256, object_key, mime_type, byte_size, width, height, created_by, created_at, deleted_at
`

type SetAssetDeletedParams struct {
	DeletedAt sql.NullInt64
	ID        int64
}

func (q *Queries) SetAssetDeleted(ctx context.Context, arg SetAssetDeletedParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, setAssetDeleted, arg.DeletedAt, arg.ID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
