// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO audit_events(actor_user_id, action, entity_type, entity_id, revision_id, metadata_json, request_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AppendAuditParams struct {
	ActorUserID  int64
	Action       string
	EntityType   string
	EntityID     int64
	RevisionID   sql.NullInt64
	MetadataJson string
	RequestID    string
	CreatedAt    int64
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.ExecContext(ctx, appendAudit,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.RevisionID,
		arg.MetadataJson,
		arg.RequestID,
		arg.CreatedAt,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_user_id, "action", entity_type, entity_id, revision_id, metadata_json, request_id, created_at FROM audit_events WHERE id > ?1 ORDER BY id LIMIT ?2
`

type ListAuditParams struct {
	AfterID  int64
	PageSize int64
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.RevisionID,
			&i.MetadataJson,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
