// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const cleanupSessions = `-- name: CleanupSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) CleanupSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, cleanupSessions, expiresAt)
	return err
}

const cleanupStates = `-- name: CleanupStates :exec
DELETE FROM oauth_states WHERE expires_at <= ?
`

func (q *Queries) CleanupStates(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, cleanupStates, expiresAt)
	return err
}

const consumeState = `-- name: ConsumeState :execrows
UPDATE oauth_states SET consumed_at = ?1
WHERE state_hash = ?2 AND consumed_at IS NULL AND expires_at > ?1
`

type ConsumeStateParams struct {
	Now       sql.NullInt64
	StateHash []byte
}

func (q *Queries) ConsumeState(ctx context.Context, arg ConsumeStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeState, arg.Now, arg.StateHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, csrf_token_hash, created_at, expires_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, user_id, token_hash, csrf_token_hash, created_at, expires_at, last_seen_at, revoked_at
`

type CreateSessionParams struct {
	UserID        int64
	TokenHash     []byte
	CsrfTokenHash []byte
	CreatedAt     int64
	ExpiresAt     int64
	LastSeenAt    int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createState = `-- name: CreateState :exec
INSERT INTO oauth_states (state_hash, created_at, expires_at) VALUES (?, ?, ?)
`

type CreateStateParams struct {
	StateHash []byte
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) error {
	_, err := q.db.ExecContext(ctx, createState, arg.StateHash, arg.CreatedAt, arg.ExpiresAt)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, token_hash, csrf_token_hash, created_at, expires_at, last_seen_at, revoked_at FROM sessions WHERE token_hash = ? AND revoked_at IS NULL AND expires_at > ?
`

type GetSessionParams struct {
	TokenHash []byte
	ExpiresAt int64
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = ? WHERE token_hash = ? AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt sql.NullInt64
	TokenHash []byte
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.TokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = ? WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	RevokedAt sql.NullInt64
	UserID    int64
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserSessions, arg.RevokedAt, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE id = ? AND last_seen_at < ? AND revoked_at IS NULL
`

type TouchSessionParams struct {
	LastSeenAt   int64
	ID           int64
	LastSeenAt_2 int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.ID, arg.LastSeenAt_2)
	return err
}
