// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const archiveContent = `-- name: ArchiveContent :exec
UPDATE content_items SET archived_at = ?1, published_revision_id = NULL,
pending_review_revision_id = NULL, editorial_state = 'draft', updated_at = ?1 WHERE id = ?2
`

type ArchiveContentParams struct {
	Now sql.NullInt64
	ID  int64
}

func (q *Queries) ArchiveContent(ctx context.Context, arg ArchiveContentParams) error {
	_, err := q.db.ExecContext(ctx, archiveContent, arg.Now, arg.ID)
	return err
}

const clearPendingRevision = `-- name: ClearPendingRevision :exec
UPDATE content_items SET editorial_state = ?, pending_review_revision_id = NULL, updated_at = ? WHERE id = ?
`

type ClearPendingRevisionParams struct {
	EditorialState string
	UpdatedAt      int64
	ID             int64
}

func (q *Queries) ClearPendingRevision(ctx context.Context, arg ClearPendingRevisionParams) error {
	_, err := q.db.ExecContext(ctx, clearPendingRevision, arg.EditorialState, arg.UpdatedAt, arg.ID)
	return err
}

const createContent = `-- name: CreateContent :one
INSERT INTO content_items(type, owner_user_id, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?) RETURNING id, type, owner_user_id, editorial_state, pending_review_revision_id, published_revision_id, created_by, first_published_at, last_published_at, created_at, updated_at, archived_at
`

type CreateContentParams struct {
	Type        string
	OwnerUserID int64
	CreatedBy   int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (ContentItem, error) {
	row := q.db.QueryRowContext(ctx, createContent,
		arg.Type,
		arg.OwnerUserID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.EditorialState,
		&i.PendingReviewRevisionID,
		&i.PublishedRevisionID,
		&i.CreatedBy,
		&i.FirstPublishedAt,
		&i.LastPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createDraft = `-- name: CreateDraft :exec
INSERT INTO content_drafts(content_id, byline_user_id, payload_schema_version, payload_json, updated_by, updated_at)
VALUES (?, ?, 1, ?, ?, ?)
`

type CreateDraftParams struct {
	ContentID    int64
	BylineUserID int64
	PayloadJson  string
	UpdatedBy    int64
	UpdatedAt    int64
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) error {
	_, err := q.db.ExecContext(ctx, createDraft,
		arg.ContentID,
		arg.BylineUserID,
		arg.PayloadJson,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const getContent = `-- name: GetContent :one
SELECT id, type, owner_user_id, editorial_state, pending_review_revision_id, published_revision_id, created_by, first_published_at, last_published_at, created_at, updated_at, archived_at FROM content_items WHERE id = ?
`

func (q *Queries) GetContent(ctx context.Context, id int64) (ContentItem, error) {
	row := q.db.QueryRowContext(ctx, getContent, id)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.EditorialState,
		&i.PendingReviewRevisionID,
		&i.PublishedRevisionID,
		&i.CreatedBy,
		&i.FirstPublishedAt,
		&i.LastPublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getDraft = `-- name: GetDraft :one
SELECT content_id, version, title, slug, summary, body_markdown, byline_user_id, language, featured, seo_title, seo_description, payload_schema_version, payload_json, updated_by, updated_at FROM content_drafts WHERE content_id = ?
`

func (q *Queries) GetDraft(ctx context.Context, contentID int64) (ContentDraft, error) {
	row := q.db.QueryRowContext(ctx, getDraft, contentID)
	var i ContentDraft
	err := row.Scan(
		&i.ContentID,
		&i.Version,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.BodyMarkdown,
		&i.BylineUserID,
		&i.Language,
		&i.Featured,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.PayloadSchemaVersion,
		&i.PayloadJson,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, content_id, revision_no, title, slug, summary, body_markdown, byline_user_id, language, featured, seo_title, seo_description, payload_schema_version, payload_json, created_by, created_at FROM content_revisions WHERE content_id = ? AND revision_no = ?
`

type GetRevisionParams struct {
	ContentID  int64
	RevisionNo int64
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (ContentRevision, error) {
	row := q.db.QueryRowContext(ctx, getRevision, arg.ContentID, arg.RevisionNo)
	var i ContentRevision
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionNo,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.BodyMarkdown,
		&i.BylineUserID,
		&i.Language,
		&i.Featured,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.PayloadSchemaVersion,
		&i.PayloadJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRevisionByID = `-- name: GetRevisionByID :one
SELECT id, content_id, revision_no, title, slug, summary, body_markdown, byline_user_id, language, featured, seo_title, seo_description, payload_schema_version, payload_json, created_by, created_at FROM content_revisions WHERE content_id = ? AND id = ?
`

type GetRevisionByIDParams struct {
	ContentID int64
	ID        int64
}

func (q *Queries) GetRevisionByID(ctx context.Context, arg GetRevisionByIDParams) (ContentRevision, error) {
	row := q.db.QueryRowContext(ctx, getRevisionByID, arg.ContentID, arg.ID)
	var i ContentRevision
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionNo,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.BodyMarkdown,
		&i.BylineUserID,
		&i.Language,
		&i.Featured,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.PayloadSchemaVersion,
		&i.PayloadJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listContent = `-- name: ListContent :many
SELECT c.id, c.type, c.owner_user_id, c.editorial_state, c.pending_review_revision_id, c.published_revision_id, c.created_by, c.first_published_at, c.last_published_at, c.created_at, c.updated_at, c.archived_at, d.title AS draft_title, r.title AS revision_title
FROM content_items c JOIN content_drafts d ON d.content_id = c.id
LEFT JOIN content_revisions r ON r.id = c.pending_review_revision_id AND r.content_id = c.id
WHERE c.id > ?1
AND (c.archived_at IS NULL OR ?2)
AND (?3 OR c.owner_user_id = ?4
OR (?5 AND c.editorial_state = 'in_review'))
ORDER BY c.id LIMIT ?6
`

type ListContentParams struct {
	AfterID         int64
	IncludeArchived interface{}
	IsAdmin         interface{}
	ActorID         int64
	IsReviewer      interface{}
	PageSize        int64
}

type ListContentRow struct {
	ID                      int64
	Type                    string
	OwnerUserID             int64
	EditorialState          string
	PendingReviewRevisionID sql.NullInt64
	PublishedRevisionID     sql.NullInt64
	CreatedBy               int64
	FirstPublishedAt        sql.NullInt64
	LastPublishedAt         sql.NullInt64
	CreatedAt               int64
	UpdatedAt               int64
	ArchivedAt              sql.NullInt64
	DraftTitle              string
	RevisionTitle           sql.NullString
}

func (q *Queries) ListContent(ctx context.Context, arg ListContentParams) ([]ListContentRow, error) {
	rows, err := q.db.QueryContext(ctx, listContent,
		arg.AfterID,
		arg.IncludeArchived,
		arg.IsAdmin,
		arg.ActorID,
		arg.IsReviewer,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentRow{}
	for rows.Next() {
		var i ListContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OwnerUserID,
			&i.EditorialState,
			&i.PendingReviewRevisionID,
			&i.PublishedRevisionID,
			&i.CreatedBy,
			&i.FirstPublishedAt,
			&i.LastPublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DraftTitle,
			&i.RevisionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, content_id, revision_no, title, slug, byline_user_id, created_by, created_at
FROM content_revisions WHERE content_id = ?1 AND revision_no > ?2
AND (?3 = 0 OR id = ?3)
ORDER BY revision_no LIMIT ?4
`

type ListRevisionsParams struct {
	ContentID      int64
	AfterNo        int64
	OnlyRevisionID interface{}
	PageSize       int64
}

type ListRevisionsRow struct {
	ID           int64
	ContentID    int64
	RevisionNo   int64
	Title        string
	Slug         string
	BylineUserID int64
	CreatedBy    int64
	CreatedAt    int64
}

func (q *Queries) ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions,
		arg.ContentID,
		arg.AfterNo,
		arg.OnlyRevisionID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevisionsRow{}
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.RevisionNo,
			&i.Title,
			&i.Slug,
			&i.BylineUserID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDraftEdited = `-- name: MarkDraftEdited :exec
UPDATE content_items SET editorial_state = CASE WHEN editorial_state = 'synced' THEN 'draft' ELSE editorial_state END, updated_at = ? WHERE id = ?
`

type MarkDraftEditedParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) MarkDraftEdited(ctx context.Context, arg MarkDraftEditedParams) error {
	_, err := q.db.ExecContext(ctx, markDraftEdited, arg.UpdatedAt, arg.ID)
	return err
}

const publishRevision = `-- name: PublishRevision :exec
UPDATE content_items SET published_revision_id = ?1, pending_review_revision_id = NULL,
editorial_state = 'synced', first_published_at = COALESCE(first_published_at, ?2),
last_published_at = ?2, updated_at = ?2 WHERE id = ?3
`

type PublishRevisionParams struct {
	RevisionID sql.NullInt64
	Now        sql.NullInt64
	ID         int64
}

func (q *Queries) PublishRevision(ctx context.Context, arg PublishRevisionParams) error {
	_, err := q.db.ExecContext(ctx, publishRevision, arg.RevisionID, arg.Now, arg.ID)
	return err
}

const restoreArchive = `-- name: RestoreArchive :exec
UPDATE content_items SET archived_at = NULL, editorial_state = 'draft', updated_at = ? WHERE id = ?
`

type RestoreArchiveParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) RestoreArchive(ctx context.Context, arg RestoreArchiveParams) error {
	_, err := q.db.ExecContext(ctx, restoreArchive, arg.UpdatedAt, arg.ID)
	return err
}

const saveDraft = `-- name: SaveDraft :execrows
UPDATE content_drafts SET title = ?1, slug = ?2, summary = ?3, body_markdown = ?4, byline_user_id = ?5, language = ?6, featured = ?7, seo_title = ?8, seo_description = ?9, payload_schema_version = ?10, payload_json = ?11,
version = version + 1, updated_by = ?12, updated_at = ?13
WHERE content_id = ?14 AND version = ?15
`

type SaveDraftParams struct {
	Title                string
	Slug                 string
	Summary              string
	BodyMarkdown         string
	BylineUserID         int64
	Language             string
	Featured             int64
	SeoTitle             string
	SeoDescription       string
	PayloadSchemaVersion int64
	PayloadJson          string
	UpdatedBy            int64
	UpdatedAt            int64
	ContentID            int64
	ExpectedVersion      int64
}

func (q *Queries) SaveDraft(ctx context.Context, arg SaveDraftParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveDraft,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.BodyMarkdown,
		arg.BylineUserID,
		arg.Language,
		arg.Featured,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.PayloadSchemaVersion,
		arg.PayloadJson,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ContentID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPendingRevision = `-- name: SetPendingRevision :exec
UPDATE content_items SET editorial_state = 'in_review', pending_review_revision_id = ?, updated_at = ? WHERE id = ?
`

type SetPendingRevisionParams struct {
	PendingReviewRevisionID sql.NullInt64
	UpdatedAt               int64
	ID                      int64
}

func (q *Queries) SetPendingRevision(ctx context.Context, arg SetPendingRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setPendingRevision, arg.PendingReviewRevisionID, arg.UpdatedAt, arg.ID)
	return err
}

const snapshotDraft = `-- name: SnapshotDraft :one
INSERT INTO content_revisions(content_id, revision_no, title, slug, summary, body_markdown, byline_user_id, language, featured, seo_title, seo_description, payload_schema_version, payload_json, created_by, created_at)
SELECT d.content_id, (SELECT COALESCE(MAX(r.revision_no), 0) + 1 FROM content_revisions r WHERE r.content_id = d.content_id),
d.title, d.slug, d.summary, d.body_markdown, d.byline_user_id, d.language, d.featured, d.seo_title, d.seo_description, d.payload_schema_version, d.payload_json, ?1, ?2
FROM content_drafts d WHERE d.content_id = ?3 RETURNING id, content_id, revision_no, title, slug, summary, body_markdown, byline_user_id, language, featured, seo_title, seo_description, payload_schema_version, payload_json, created_by, created_at
`

type SnapshotDraftParams struct {
	ActorID   int64
	Now       int64
	ContentID int64
}

func (q *Queries) SnapshotDraft(ctx context.Context, arg SnapshotDraftParams) (ContentRevision, error) {
	row := q.db.QueryRowContext(ctx, snapshotDraft, arg.ActorID, arg.Now, arg.ContentID)
	var i ContentRevision
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionNo,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.BodyMarkdown,
		&i.BylineUserID,
		&i.Language,
		&i.Featured,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.PayloadSchemaVersion,
		&i.PayloadJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const unpublishContent = `-- name: UnpublishContent :exec
UPDATE content_items SET published_revision_id = NULL, pending_review_revision_id = NULL,
editorial_state = 'draft', updated_at = ? WHERE id = ?
`

type UnpublishContentParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UnpublishContent(ctx context.Context, arg UnpublishContentParams) error {
	_, err := q.db.ExecContext(ctx, unpublishContent, arg.UpdatedAt, arg.ID)
	return err
}
