// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editorial_ux.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"
)

const authorSummaries = `-- name: AuthorSummaries :many
SELECT user_id, slug, display_name, avatar_url FROM author_profiles
WHERE user_id IN (/*SLICE:ids*/?) ORDER BY user_id
`

type AuthorSummariesRow struct {
	UserID      int64
	Slug        string
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) AuthorSummaries(ctx context.Context, ids []int64) ([]AuthorSummariesRow, error) {
	query := authorSummaries
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthorSummariesRow{}
	for rows.Next() {
		var i AuthorSummariesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Slug,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, content_id, revision_id, reviewer_user_id, decision, comment_markdown, created_at FROM content_reviews WHERE id = ?
`

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (ContentReview, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i ContentReview
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.ReviewerUserID,
		&i.Decision,
		&i.CommentMarkdown,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsByIDs = `-- name: GetTagsByIDs :many
SELECT id, name, normalized_name, slug, description, created_by, created_at, updated_at FROM tags WHERE id IN (/*SLICE:ids*/?) ORDER BY id
`

func (q *Queries) GetTagsByIDs(ctx context.Context, ids []int64) ([]Tag, error) {
	query := getTagsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestContentReview = `-- name: LatestContentReview :one
SELECT id, content_id, revision_id, reviewer_user_id, decision, comment_markdown, created_at FROM content_reviews WHERE content_id = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) LatestContentReview(ctx context.Context, contentID int64) (ContentReview, error) {
	row := q.db.QueryRowContext(ctx, latestContentReview, contentID)
	var i ContentReview
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.ReviewerUserID,
		&i.Decision,
		&i.CommentMarkdown,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT user_id, slug, display_name, avatar_url FROM author_profiles
WHERE user_id > ?1
AND (?2 = '' OR instr(lower(display_name), lower(?2)) > 0 OR instr(slug, lower(?2)) > 0)
ORDER BY user_id LIMIT ?3
`

type ListAuthorsParams struct {
	AfterID  int64
	Search   interface{}
	PageSize int64
}

type ListAuthorsRow struct {
	UserID      int64
	Slug        string
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.AfterID, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsRow{}
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Slug,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionLabels = `-- name: RevisionLabels :many
SELECT id, title, revision_no FROM content_revisions WHERE id IN (/*SLICE:ids*/?)
`

type RevisionLabelsRow struct {
	ID         int64
	Title      string
	RevisionNo int64
}

func (q *Queries) RevisionLabels(ctx context.Context, ids []int64) ([]RevisionLabelsRow, error) {
	query := revisionLabels
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionLabelsRow{}
	for rows.Next() {
		var i RevisionLabelsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.RevisionNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topicTargetSummaries = `-- name: TopicTargetSummaries :many
SELECT c.id, c.type, c.owner_user_id, c.editorial_state, c.pending_review_revision_id, c.published_revision_id, c.created_by, c.first_published_at, c.last_published_at, c.created_at, c.updated_at, c.archived_at, d.title AS draft_title, p.title AS published_title, r.title AS pending_title
FROM content_items c JOIN content_drafts d ON d.content_id=c.id
LEFT JOIN content_revisions p ON p.id=c.published_revision_id AND p.content_id=c.id
LEFT JOIN content_revisions r ON r.id=c.pending_review_revision_id AND r.content_id=c.id
WHERE c.id IN (/*SLICE:ids*/?)
`

type TopicTargetSummariesRow struct {
	ID                      int64
	Type                    string
	OwnerUserID             int64
	EditorialState          string
	PendingReviewRevisionID sql.NullInt64
	PublishedRevisionID     sql.NullInt64
	CreatedBy               int64
	FirstPublishedAt        sql.NullInt64
	LastPublishedAt         sql.NullInt64
	CreatedAt               int64
	UpdatedAt               int64
	ArchivedAt              sql.NullInt64
	DraftTitle              string
	PublishedTitle          sql.NullString
	PendingTitle            sql.NullString
}

func (q *Queries) TopicTargetSummaries(ctx context.Context, ids []int64) ([]TopicTargetSummariesRow, error) {
	query := topicTargetSummaries
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopicTargetSummariesRow{}
	for rows.Next() {
		var i TopicTargetSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OwnerUserID,
			&i.EditorialState,
			&i.PendingReviewRevisionID,
			&i.PublishedRevisionID,
			&i.CreatedBy,
			&i.FirstPublishedAt,
			&i.LastPublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.DraftTitle,
			&i.PublishedTitle,
			&i.PendingTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
