// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const legacyContentCollision = `-- name: LegacyContentCollision :one
SELECT count(*) FROM content_items c JOIN content_drafts d ON d.content_id=c.id
WHERE c.type=?1 AND d.slug=?2
`

type LegacyContentCollisionParams struct {
	ContentType string
	Slug        string
}

func (q *Queries) LegacyContentCollision(ctx context.Context, arg LegacyContentCollisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, legacyContentCollision, arg.ContentType, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const legacyOwnedRoute = `-- name: LegacyOwnedRoute :one
SELECT count(*) FROM content_routes WHERE path=?
`

func (q *Queries) LegacyOwnedRoute(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, legacyOwnedRoute, path)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const restoreLegacyPublicationDates = `-- name: RestoreLegacyPublicationDates :exec
UPDATE content_items SET first_published_at=?,last_published_at=?,created_at=?,updated_at=? WHERE id=?
`

type RestoreLegacyPublicationDatesParams struct {
	FirstPublishedAt sql.NullInt64
	LastPublishedAt  sql.NullInt64
	CreatedAt        int64
	UpdatedAt        int64
	ID               int64
}

// Offline importer only. Publication service calls the date update in its own
// direct-publish transaction; no handler exposes it and no Revision is edited.
func (q *Queries) RestoreLegacyPublicationDates(ctx context.Context, arg RestoreLegacyPublicationDatesParams) error {
	_, err := q.db.ExecContext(ctx, restoreLegacyPublicationDates,
		arg.FirstPublishedAt,
		arg.LastPublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
