// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"database/sql"
)

type AuthorProfile struct {
	UserID      int64
	Slug        string
	DisplayName string
	BioMarkdown string
	AvatarUrl   string
	WebsiteUrl  string
	CreatedAt   int64
	UpdatedAt   int64
}

type OauthState struct {
	StateHash  []byte
	CreatedAt  int64
	ExpiresAt  int64
	ConsumedAt sql.NullInt64
}

type Session struct {
	ID            int64
	UserID        int64
	TokenHash     []byte
	CsrfTokenHash []byte
	CreatedAt     int64
	ExpiresAt     int64
	LastSeenAt    int64
	RevokedAt     sql.NullInt64
}

type User struct {
	ID           int64
	GithubUserID int64
	GithubLogin  string
	Role         string
	Status       string
	CreatedAt    int64
	UpdatedAt    int64
	LastLoginAt  sql.NullInt64
}
