// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_ux.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"strings"
)

const productMetadata = `-- name: ProductMetadata :many
SELECT c.id,c.owner_user_id,
d.summary AS draft_summary,d.payload_json AS draft_payload,d.language AS draft_language,d.featured AS draft_featured,
r.summary AS revision_summary,r.payload_json AS revision_payload,r.language AS revision_language,r.featured AS revision_featured,
(SELECT count(*) FROM draft_topic_entries WHERE topic_content_id=c.id) AS draft_entry_count,
(SELECT count(*) FROM revision_topic_entries WHERE topic_revision_id=r.id) AS revision_entry_count
FROM content_items c JOIN content_drafts d ON d.content_id=c.id
LEFT JOIN content_revisions r ON r.id=c.pending_review_revision_id AND r.content_id=c.id
WHERE c.id IN (/*SLICE:ids*/?) ORDER BY c.id
`

type ProductMetadataRow struct {
	ID                 int64
	OwnerUserID        int64
	DraftSummary       string
	DraftPayload       string
	DraftLanguage      string
	DraftFeatured      int64
	RevisionSummary    sql.NullString
	RevisionPayload    sql.NullString
	RevisionLanguage   sql.NullString
	RevisionFeatured   sql.NullInt64
	DraftEntryCount    int64
	RevisionEntryCount int64
}

// Bounded product metadata for IDs already admitted by ListContent policy.
// No Markdown body is selected, and non-owner Reviewer projections use pending
// immutable metadata rather than someone else's mutable Draft.
func (q *Queries) ProductMetadata(ctx context.Context, ids []int64) ([]ProductMetadataRow, error) {
	query := productMetadata
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductMetadataRow{}
	for rows.Next() {
		var i ProductMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.DraftSummary,
			&i.DraftPayload,
			&i.DraftLanguage,
			&i.DraftFeatured,
			&i.RevisionSummary,
			&i.RevisionPayload,
			&i.RevisionLanguage,
			&i.RevisionFeatured,
			&i.DraftEntryCount,
			&i.RevisionEntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productTags = `-- name: ProductTags :many
SELECT c.id AS content_id,t.id,t.name,t.slug
FROM content_items c
LEFT JOIN draft_tags d ON d.content_id=c.id AND (?1 OR c.owner_user_id=?2)
LEFT JOIN revision_tags r ON r.revision_id=c.pending_review_revision_id AND NOT (?1 OR c.owner_user_id=?2)
JOIN tags t ON t.id=COALESCE(d.tag_id,r.tag_id)
WHERE c.id IN (/*SLICE:ids*/?) ORDER BY c.id,t.id
`

type ProductTagsParams struct {
	IsAdmin interface{}
	ActorID int64
	Ids     []int64
}

type ProductTagsRow struct {
	ContentID int64
	ID        int64
	Name      string
	Slug      string
}

func (q *Queries) ProductTags(ctx context.Context, arg ProductTagsParams) ([]ProductTagsRow, error) {
	query := productTags
	var queryParams []interface{}
	queryParams = append(queryParams, arg.IsAdmin)
	queryParams = append(queryParams, arg.ActorID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductTagsRow{}
	for rows.Next() {
		var i ProductTagsRow
		if err := rows.Scan(
			&i.ContentID,
			&i.ID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productTopics = `-- name: ProductTopics :many
SELECT target.id AS target_content_id,c.id,
CAST(CASE WHEN ?1 = 1 THEN d.title ELSE r.title END AS TEXT) AS title
FROM content_items c JOIN content_drafts d ON d.content_id=c.id
LEFT JOIN content_revisions r ON r.id=c.published_revision_id AND r.content_id=c.id
LEFT JOIN draft_topic_entries e ON e.topic_content_id=c.id AND ?1
LEFT JOIN revision_topic_entries p ON p.topic_revision_id=r.id AND NOT ?1
JOIN content_items target ON target.id=COALESCE(e.target_content_id,p.target_content_id)
WHERE c.type='topic' AND c.archived_at IS NULL AND target.id IN (/*SLICE:ids*/?)
ORDER BY target_content_id,c.id LIMIT 10001
`

type ProductTopicsParams struct {
	IsAdmin interface{}
	Ids     []int64
}

type ProductTopicsRow struct {
	TargetContentID int64
	ID              int64
	Title           string
}

func (q *Queries) ProductTopics(ctx context.Context, arg ProductTopicsParams) ([]ProductTopicsRow, error) {
	query := productTopics
	var queryParams []interface{}
	queryParams = append(queryParams, arg.IsAdmin)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductTopicsRow{}
	for rows.Next() {
		var i ProductTopicsRow
		if err := rows.Scan(&i.TargetContentID, &i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
