// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publication.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const createPublicationJob = `-- name: CreatePublicationJob :one
INSERT INTO publication_jobs(generation,created_at,updated_at) VALUES (?,?,?) RETURNING id, generation, state, snapshot_key, snapshot_sha256, attempts, last_error, next_attempt_at, created_at, updated_at, triggered_at
`

type CreatePublicationJobParams struct {
	Generation int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreatePublicationJob(ctx context.Context, arg CreatePublicationJobParams) (PublicationJob, error) {
	row := q.db.QueryRowContext(ctx, createPublicationJob, arg.Generation, arg.CreatedAt, arg.UpdatedAt)
	var i PublicationJob
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.State,
		&i.SnapshotKey,
		&i.SnapshotSha256,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggeredAt,
	)
	return i, err
}

const failPublicationJob = `-- name: FailPublicationJob :execrows
UPDATE publication_jobs SET state='failed',attempts=attempts+1,last_error=?,next_attempt_at=?,updated_at=?
WHERE id=? AND state IN ('pending','snapshot_uploaded','failed')
`

type FailPublicationJobParams struct {
	LastError     string
	NextAttemptAt sql.NullInt64
	UpdatedAt     int64
	ID            int64
}

func (q *Queries) FailPublicationJob(ctx context.Context, arg FailPublicationJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPublicationJob,
		arg.LastError,
		arg.NextAttemptAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPublicationJob = `-- name: GetPublicationJob :one
SELECT id, generation, state, snapshot_key, snapshot_sha256, attempts, last_error, next_attempt_at, created_at, updated_at, triggered_at FROM publication_jobs WHERE id=?
`

func (q *Queries) GetPublicationJob(ctx context.Context, id int64) (PublicationJob, error) {
	row := q.db.QueryRowContext(ctx, getPublicationJob, id)
	var i PublicationJob
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.State,
		&i.SnapshotKey,
		&i.SnapshotSha256,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggeredAt,
	)
	return i, err
}

const getSiteState = `-- name: GetSiteState :one
SELECT id, publication_generation, updated_at FROM site_state WHERE id=1
`

func (q *Queries) GetSiteState(ctx context.Context) (SiteState, error) {
	row := q.db.QueryRowContext(ctx, getSiteState)
	var i SiteState
	err := row.Scan(&i.ID, &i.PublicationGeneration, &i.UpdatedAt)
	return i, err
}

const incrementGeneration = `-- name: IncrementGeneration :one
UPDATE site_state SET publication_generation=publication_generation+1, updated_at=? WHERE id=1 RETURNING publication_generation
`

func (q *Queries) IncrementGeneration(ctx context.Context, updatedAt int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementGeneration, updatedAt)
	var publication_generation int64
	err := row.Scan(&publication_generation)
	return publication_generation, err
}

const latestPublicationJob = `-- name: LatestPublicationJob :one
SELECT id, generation, state, snapshot_key, snapshot_sha256, attempts, last_error, next_attempt_at, created_at, updated_at, triggered_at FROM publication_jobs ORDER BY generation DESC LIMIT 1
`

func (q *Queries) LatestPublicationJob(ctx context.Context) (PublicationJob, error) {
	row := q.db.QueryRowContext(ctx, latestPublicationJob)
	var i PublicationJob
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.State,
		&i.SnapshotKey,
		&i.SnapshotSha256,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggeredAt,
	)
	return i, err
}

const listPublicationJobs = `-- name: ListPublicationJobs :many
SELECT id, generation, state, snapshot_key, snapshot_sha256, attempts, last_error, next_attempt_at, created_at, updated_at, triggered_at FROM publication_jobs WHERE id > ?1 ORDER BY id LIMIT ?2
`

type ListPublicationJobsParams struct {
	AfterID  int64
	PageSize int64
}

func (q *Queries) ListPublicationJobs(ctx context.Context, arg ListPublicationJobsParams) ([]PublicationJob, error) {
	rows, err := q.db.QueryContext(ctx, listPublicationJobs, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicationJob{}
	for rows.Next() {
		var i PublicationJob
		if err := rows.Scan(
			&i.ID,
			&i.Generation,
			&i.State,
			&i.SnapshotKey,
			&i.SnapshotSha256,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TriggeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBuildTriggered = `-- name: MarkBuildTriggered :execrows
UPDATE publication_jobs SET state='build_triggered',last_error='',next_attempt_at=NULL,updated_at=?1,triggered_at=?1
WHERE id=?2 AND state IN ('snapshot_uploaded','failed')
`

type MarkBuildTriggeredParams struct {
	Now int64
	ID  int64
}

func (q *Queries) MarkBuildTriggered(ctx context.Context, arg MarkBuildTriggeredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markBuildTriggered, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markSnapshotUploaded = `-- name: MarkSnapshotUploaded :execrows
UPDATE publication_jobs SET state='snapshot_uploaded',snapshot_key=?,snapshot_sha256=?,last_error='',next_attempt_at=NULL,updated_at=?
WHERE id=? AND state IN ('pending','failed')
`

type MarkSnapshotUploadedParams struct {
	SnapshotKey    sql.NullString
	SnapshotSha256 sql.NullString
	UpdatedAt      int64
	ID             int64
}

func (q *Queries) MarkSnapshotUploaded(ctx context.Context, arg MarkSnapshotUploadedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSnapshotUploaded,
		arg.SnapshotKey,
		arg.SnapshotSha256,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const publishedContentBylineExists = `-- name: PublishedContentBylineExists :one
SELECT EXISTS(SELECT 1 FROM content_items c JOIN content_revisions r ON r.id=c.published_revision_id AND r.content_id=c.id
WHERE c.archived_at IS NULL AND r.byline_user_id=?) AS found
`

func (q *Queries) PublishedContentBylineExists(ctx context.Context, bylineUserID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, publishedContentBylineExists, bylineUserID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const publishedRevisionUsesTag = `-- name: PublishedRevisionUsesTag :one
SELECT EXISTS(SELECT 1 FROM content_items c JOIN revision_tags t ON t.revision_id=c.published_revision_id
WHERE c.archived_at IS NULL AND t.tag_id=?) AS found
`

func (q *Queries) PublishedRevisionUsesTag(ctx context.Context, tagID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, publishedRevisionUsesTag, tagID)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const retryPublicationJob = `-- name: RetryPublicationJob :execrows
UPDATE publication_jobs SET state=CASE WHEN snapshot_key IS NULL THEN 'pending' ELSE 'snapshot_uploaded' END,
attempts=0,last_error='',next_attempt_at=NULL,updated_at=? WHERE id=? AND state='failed'
`

type RetryPublicationJobParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) RetryPublicationJob(ctx context.Context, arg RetryPublicationJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryPublicationJob, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedePublicationJobs = `-- name: SupersedePublicationJobs :exec
UPDATE publication_jobs SET state='superseded',next_attempt_at=NULL,updated_at=?1
WHERE generation < ?2 AND state IN ('pending','snapshot_uploaded','failed')
`

type SupersedePublicationJobsParams struct {
	Now        int64
	Generation int64
}

func (q *Queries) SupersedePublicationJobs(ctx context.Context, arg SupersedePublicationJobsParams) error {
	_, err := q.db.ExecContext(ctx, supersedePublicationJobs, arg.Now, arg.Generation)
	return err
}
