// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package dbsqlc

import (
	"context"
)

const createReview = `-- name: CreateReview :one
INSERT INTO content_reviews(content_id, revision_id, reviewer_user_id, decision, comment_markdown, created_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, content_id, revision_id, reviewer_user_id, decision, comment_markdown, created_at
`

type CreateReviewParams struct {
	ContentID       int64
	RevisionID      int64
	ReviewerUserID  int64
	Decision        string
	CommentMarkdown string
	CreatedAt       int64
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (ContentReview, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.ContentID,
		arg.RevisionID,
		arg.ReviewerUserID,
		arg.Decision,
		arg.CommentMarkdown,
		arg.CreatedAt,
	)
	var i ContentReview
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.ReviewerUserID,
		&i.Decision,
		&i.CommentMarkdown,
		&i.CreatedAt,
	)
	return i, err
}

const getRevisionReview = `-- name: GetRevisionReview :one
SELECT id, content_id, revision_id, reviewer_user_id, decision, comment_markdown, created_at FROM content_reviews WHERE revision_id = ?
`

func (q *Queries) GetRevisionReview(ctx context.Context, revisionID int64) (ContentReview, error) {
	row := q.db.QueryRowContext(ctx, getRevisionReview, revisionID)
	var i ContentReview
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.RevisionID,
		&i.ReviewerUserID,
		&i.Decision,
		&i.CommentMarkdown,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingReviews = `-- name: ListPendingReviews :many
SELECT r.id, r.content_id, r.revision_no, r.title, r.byline_user_id, r.created_at, c.owner_user_id
FROM content_items c JOIN content_revisions r ON r.id = c.pending_review_revision_id AND r.content_id = c.id
WHERE r.id > ?1 AND c.editorial_state = 'in_review' AND c.archived_at IS NULL
AND (?2 OR (c.owner_user_id != ?3 AND r.byline_user_id != ?3))
ORDER BY r.id LIMIT ?4
`

type ListPendingReviewsParams struct {
	AfterID  int64
	IsAdmin  interface{}
	ActorID  int64
	PageSize int64
}

type ListPendingReviewsRow struct {
	ID           int64
	ContentID    int64
	RevisionNo   int64
	Title        string
	BylineUserID int64
	CreatedAt    int64
	OwnerUserID  int64
}

func (q *Queries) ListPendingReviews(ctx context.Context, arg ListPendingReviewsParams) ([]ListPendingReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReviews,
		arg.AfterID,
		arg.IsAdmin,
		arg.ActorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingReviewsRow{}
	for rows.Next() {
		var i ListPendingReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.RevisionNo,
			&i.Title,
			&i.BylineUserID,
			&i.CreatedAt,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewHistory = `-- name: ListReviewHistory :many
SELECT id, content_id, revision_id, reviewer_user_id, decision, comment_markdown, created_at FROM content_reviews WHERE id > ?1 ORDER BY id LIMIT ?2
`

type ListReviewHistoryParams struct {
	AfterID  int64
	PageSize int64
}

func (q *Queries) ListReviewHistory(ctx context.Context, arg ListReviewHistoryParams) ([]ContentReview, error) {
	rows, err := q.db.QueryContext(ctx, listReviewHistory, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentReview{}
	for rows.Next() {
		var i ContentReview
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.RevisionID,
			&i.ReviewerUserID,
			&i.Decision,
			&i.CommentMarkdown,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
