// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const claimCanonical = `-- name: ClaimCanonical :exec
INSERT INTO content_routes(content_id, path, kind, created_at) VALUES (?, ?, 'canonical', ?)
ON CONFLICT(path) DO UPDATE SET kind = 'canonical'
`

type ClaimCanonicalParams struct {
	ContentID int64
	Path      string
	CreatedAt int64
}

func (q *Queries) ClaimCanonical(ctx context.Context, arg ClaimCanonicalParams) error {
	_, err := q.db.ExecContext(ctx, claimCanonical, arg.ContentID, arg.Path, arg.CreatedAt)
	return err
}

const contentRoutes = `-- name: ContentRoutes :many
SELECT id, content_id, path, kind, created_at FROM content_routes WHERE content_id = ?1 AND id > ?2
ORDER BY id LIMIT ?3
`

type ContentRoutesParams struct {
	ContentID int64
	AfterID   int64
	PageSize  int64
}

func (q *Queries) ContentRoutes(ctx context.Context, arg ContentRoutesParams) ([]ContentRoute, error) {
	rows, err := q.db.QueryContext(ctx, contentRoutes, arg.ContentID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentRoute{}
	for rows.Next() {
		var i ContentRoute
		if err := rows.Scan(
			&i.ID,
			&i.ContentID,
			&i.Path,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const demoteCanonical = `-- name: DemoteCanonical :exec
UPDATE content_routes SET kind = 'redirect' WHERE content_id = ? AND kind = 'canonical'
`

func (q *Queries) DemoteCanonical(ctx context.Context, contentID int64) error {
	_, err := q.db.ExecContext(ctx, demoteCanonical, contentID)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, content_id, path, kind, created_at FROM content_routes WHERE path = ?
`

func (q *Queries) GetRoute(ctx context.Context, path string) (ContentRoute, error) {
	row := q.db.QueryRowContext(ctx, getRoute, path)
	var i ContentRoute
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Path,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const resolveRoute = `-- name: ResolveRoute :one
SELECT original.content_id, original.kind, canonical.path AS canonical_path, c.published_revision_id, c.archived_at
FROM content_routes original JOIN content_items c ON c.id = original.content_id
JOIN content_routes canonical ON canonical.content_id = c.id AND canonical.kind = 'canonical'
WHERE original.path = ?
`

type ResolveRouteRow struct {
	ContentID           int64
	Kind                string
	CanonicalPath       string
	PublishedRevisionID sql.NullInt64
	ArchivedAt          sql.NullInt64
}

func (q *Queries) ResolveRoute(ctx context.Context, path string) (ResolveRouteRow, error) {
	row := q.db.QueryRowContext(ctx, resolveRoute, path)
	var i ResolveRouteRow
	err := row.Scan(
		&i.ContentID,
		&i.Kind,
		&i.CanonicalPath,
		&i.PublishedRevisionID,
		&i.ArchivedAt,
	)
	return i, err
}
