// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const countPublishedContent = `-- name: CountPublishedContent :one
SELECT count(*) FROM content_items WHERE published_revision_id IS NOT NULL AND archived_at IS NULL
`

// The public projection exclusively selects immutable published revisions.
func (q *Queries) CountPublishedContent(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedContent)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const exportPublishedContent = `-- name: ExportPublishedContent :many
SELECT c.type, c.first_published_at, c.last_published_at, r.id, r.content_id, r.revision_no, r.title, r.slug, r.summary, r.body_markdown, r.byline_user_id, r.language, r.featured, r.seo_title, r.seo_description, r.payload_schema_version, r.payload_json, r.created_by, r.created_at, r.cover_asset_id,
(SELECT path FROM content_routes WHERE content_id=c.id AND kind='canonical') AS canonical_path
FROM content_items c JOIN content_revisions r ON r.id=c.published_revision_id AND r.content_id=c.id
WHERE c.published_revision_id IS NOT NULL AND c.archived_at IS NULL AND c.id > ?1
ORDER BY c.id LIMIT ?2
`

type ExportPublishedContentParams struct {
	AfterID  int64
	PageSize int64
}

type ExportPublishedContentRow struct {
	Type                 string
	FirstPublishedAt     sql.NullInt64
	LastPublishedAt      sql.NullInt64
	ID                   int64
	ContentID            int64
	RevisionNo           int64
	Title                string
	Slug                 string
	Summary              string
	BodyMarkdown         string
	BylineUserID         int64
	Language             string
	Featured             int64
	SeoTitle             string
	SeoDescription       string
	PayloadSchemaVersion int64
	PayloadJson          string
	CreatedBy            int64
	CreatedAt            int64
	CoverAssetID         sql.NullInt64
	CanonicalPath        string
}

func (q *Queries) ExportPublishedContent(ctx context.Context, arg ExportPublishedContentParams) ([]ExportPublishedContentRow, error) {
	rows, err := q.db.QueryContext(ctx, exportPublishedContent, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportPublishedContentRow{}
	for rows.Next() {
		var i ExportPublishedContentRow
		if err := rows.Scan(
			&i.Type,
			&i.FirstPublishedAt,
			&i.LastPublishedAt,
			&i.ID,
			&i.ContentID,
			&i.RevisionNo,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.BodyMarkdown,
			&i.BylineUserID,
			&i.Language,
			&i.Featured,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.PayloadSchemaVersion,
			&i.PayloadJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CoverAssetID,
			&i.CanonicalPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPublishedRoutes = `-- name: ExportPublishedRoutes :many
SELECT r.path,r.kind,r.content_id FROM content_routes r JOIN content_items c ON c.id=r.content_id
WHERE c.published_revision_id IS NOT NULL AND c.archived_at IS NULL AND r.path > ?1
ORDER BY r.path LIMIT ?2
`

type ExportPublishedRoutesParams struct {
	AfterPath string
	PageSize  int64
}

type ExportPublishedRoutesRow struct {
	Path      string
	Kind      string
	ContentID int64
}

func (q *Queries) ExportPublishedRoutes(ctx context.Context, arg ExportPublishedRoutesParams) ([]ExportPublishedRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, exportPublishedRoutes, arg.AfterPath, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportPublishedRoutesRow{}
	for rows.Next() {
		var i ExportPublishedRoutesRow
		if err := rows.Scan(&i.Path, &i.Kind, &i.ContentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
