// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomy.sql

package dbsqlc

import (
	"context"
	"strings"
)

const addDraftTag = `-- name: AddDraftTag :exec
INSERT INTO draft_tags(content_id, tag_id) VALUES (?, ?)
`

type AddDraftTagParams struct {
	ContentID int64
	TagID     int64
}

func (q *Queries) AddDraftTag(ctx context.Context, arg AddDraftTagParams) error {
	_, err := q.db.ExecContext(ctx, addDraftTag, arg.ContentID, arg.TagID)
	return err
}

const addDraftTopicEntry = `-- name: AddDraftTopicEntry :exec
INSERT INTO draft_topic_entries(topic_content_id, position, target_content_id) VALUES (?, ?, ?)
`

type AddDraftTopicEntryParams struct {
	TopicContentID  int64
	Position        int64
	TargetContentID int64
}

func (q *Queries) AddDraftTopicEntry(ctx context.Context, arg AddDraftTopicEntryParams) error {
	_, err := q.db.ExecContext(ctx, addDraftTopicEntry, arg.TopicContentID, arg.Position, arg.TargetContentID)
	return err
}

const countCuratedContent = `-- name: CountCuratedContent :one
SELECT count(*) FROM content_items WHERE id IN (/*SLICE:ids*/?) AND type = 'curated_article'
`

func (q *Queries) CountCuratedContent(ctx context.Context, ids []int64) (int64, error) {
	query := countCuratedContent
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExistingTags = `-- name: CountExistingTags :one
SELECT count(*) FROM tags WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) CountExistingTags(ctx context.Context, ids []int64) (int64, error) {
	query := countExistingTags
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags(name, normalized_name, slug, description, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, name, normalized_name, slug, description, created_by, created_at, updated_at
`

type CreateTagParams struct {
	Name           string
	NormalizedName string
	Slug           string
	Description    string
	CreatedBy      int64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.Name,
		arg.NormalizedName,
		arg.Slug,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftTags = `-- name: DeleteDraftTags :exec
DELETE FROM draft_tags WHERE content_id = ?
`

func (q *Queries) DeleteDraftTags(ctx context.Context, contentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDraftTags, contentID)
	return err
}

const deleteDraftTopicEntries = `-- name: DeleteDraftTopicEntries :exec
DELETE FROM draft_topic_entries WHERE topic_content_id = ?
`

func (q *Queries) DeleteDraftTopicEntries(ctx context.Context, topicContentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDraftTopicEntries, topicContentID)
	return err
}

const draftTagIDs = `-- name: DraftTagIDs :many
SELECT tag_id FROM draft_tags WHERE content_id = ? ORDER BY tag_id
`

func (q *Queries) DraftTagIDs(ctx context.Context, contentID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, draftTagIDs, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var tag_id int64
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const draftTopicEntries = `-- name: DraftTopicEntries :many
SELECT position, target_content_id FROM draft_topic_entries WHERE topic_content_id = ? ORDER BY position
`

type DraftTopicEntriesRow struct {
	Position        int64
	TargetContentID int64
}

func (q *Queries) DraftTopicEntries(ctx context.Context, topicContentID int64) ([]DraftTopicEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, draftTopicEntries, topicContentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DraftTopicEntriesRow{}
	for rows.Next() {
		var i DraftTopicEntriesRow
		if err := rows.Scan(&i.Position, &i.TargetContentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTagConflict = `-- name: FindTagConflict :one
SELECT count(*) FROM tags WHERE id != ?1 AND (normalized_name = ?2 OR slug = ?3)
`

type FindTagConflictParams struct {
	ExcludeID      int64
	NormalizedName string
	Slug           string
}

func (q *Queries) FindTagConflict(ctx context.Context, arg FindTagConflictParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findTagConflict, arg.ExcludeID, arg.NormalizedName, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, normalized_name, slug, description, created_by, created_at, updated_at FROM tags WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, normalized_name, slug, description, created_by, created_at, updated_at FROM tags WHERE id > ?1 ORDER BY id LIMIT ?2
`

type ListTagsParams struct {
	AfterID  int64
	PageSize int64
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishedNoteGroupMetadata = `-- name: PublishedNoteGroupMetadata :many
SELECT r.payload_json FROM content_items c JOIN content_revisions r ON r.id=c.published_revision_id AND r.content_id=c.id
WHERE c.type='note' AND c.archived_at IS NULL AND c.id != ?1
AND json_extract(r.payload_json, '$.groupSlug') = ?2
`

type PublishedNoteGroupMetadataParams struct {
	ContentID int64
	GroupSlug string
}

func (q *Queries) PublishedNoteGroupMetadata(ctx context.Context, arg PublishedNoteGroupMetadataParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, publishedNoteGroupMetadata, arg.ContentID, arg.GroupSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var payload_json string
		if err := rows.Scan(&payload_json); err != nil {
			return nil, err
		}
		items = append(items, payload_json)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionTagIDs = `-- name: RevisionTagIDs :many
SELECT tag_id FROM revision_tags WHERE revision_id = ? ORDER BY tag_id
`

func (q *Queries) RevisionTagIDs(ctx context.Context, revisionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, revisionTagIDs, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var tag_id int64
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionTopicEntries = `-- name: RevisionTopicEntries :many
SELECT position, target_content_id FROM revision_topic_entries WHERE topic_revision_id = ? ORDER BY position
`

type RevisionTopicEntriesRow struct {
	Position        int64
	TargetContentID int64
}

func (q *Queries) RevisionTopicEntries(ctx context.Context, topicRevisionID int64) ([]RevisionTopicEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, revisionTopicEntries, topicRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionTopicEntriesRow{}
	for rows.Next() {
		var i RevisionTopicEntriesRow
		if err := rows.Scan(&i.Position, &i.TargetContentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotTags = `-- name: SnapshotTags :exec
INSERT INTO revision_tags(revision_id, tag_id) SELECT ?1, tag_id FROM draft_tags WHERE content_id = ?2
`

type SnapshotTagsParams struct {
	RevisionID int64
	ContentID  int64
}

func (q *Queries) SnapshotTags(ctx context.Context, arg SnapshotTagsParams) error {
	_, err := q.db.ExecContext(ctx, snapshotTags, arg.RevisionID, arg.ContentID)
	return err
}

const snapshotTopicEntries = `-- name: SnapshotTopicEntries :exec
INSERT INTO revision_topic_entries(topic_revision_id, position, target_content_id)
SELECT ?1, position, target_content_id FROM draft_topic_entries WHERE topic_content_id = ?2
`

type SnapshotTopicEntriesParams struct {
	RevisionID int64
	ContentID  int64
}

func (q *Queries) SnapshotTopicEntries(ctx context.Context, arg SnapshotTopicEntriesParams) error {
	_, err := q.db.ExecContext(ctx, snapshotTopicEntries, arg.RevisionID, arg.ContentID)
	return err
}

const unpublishableTopicTargets = `-- name: UnpublishableTopicTargets :one
SELECT count(*) FROM revision_topic_entries e JOIN content_items c ON c.id = e.target_content_id
WHERE e.topic_revision_id = ? AND (c.type != 'curated_article' OR c.published_revision_id IS NULL OR c.archived_at IS NOT NULL)
`

func (q *Queries) UnpublishableTopicTargets(ctx context.Context, topicRevisionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, unpublishableTopicTargets, topicRevisionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = ?, normalized_name = ?, slug = ?, description = ?, updated_at = ? WHERE id = ? RETURNING id, name, normalized_name, slug, description, created_by, created_at, updated_at
`

type UpdateTagParams struct {
	Name           string
	NormalizedName string
	Slug           string
	Description    string
	UpdatedAt      int64
	ID             int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.Name,
		arg.NormalizedName,
		arg.Slug,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
