// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND status = 'active'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO author_profiles (user_id, slug, display_name, avatar_url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProfileParams struct {
	UserID      int64
	Slug        string
	DisplayName string
	AvatarUrl   string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile,
		arg.UserID,
		arg.Slug,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (github_user_id, github_login, role, status, created_at, updated_at, last_login_at)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, github_user_id, github_login, role, status, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	GithubUserID int64
	GithubLogin  string
	Role         string
	Status       string
	CreatedAt    int64
	UpdatedAt    int64
	LastLoginAt  sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.GithubUserID,
		arg.GithubLogin,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, slug, display_name, bio_markdown, avatar_url, website_url, created_at, updated_at FROM author_profiles WHERE user_id = ?
`

func (q *Queries) GetProfile(ctx context.Context, userID int64) (AuthorProfile, error) {
	row := q.db.QueryRowContext(ctx, getProfile, userID)
	var i AuthorProfile
	err := row.Scan(
		&i.UserID,
		&i.Slug,
		&i.DisplayName,
		&i.BioMarkdown,
		&i.AvatarUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, github_user_id, github_login, role, status, created_at, updated_at, last_login_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_user_id, github_login, role, status, created_at, updated_at, last_login_at FROM users WHERE github_user_id = ?
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubUserID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGitHubID, githubUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_user_id, github_login, role, status, created_at, updated_at, last_login_at FROM users WHERE id > ?1 ORDER BY id LIMIT ?2
`

type ListUsersParams struct {
	AfterID  int64
	PageSize int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GithubUserID,
			&i.GithubLogin,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshLogin = `-- name: RefreshLogin :one
UPDATE users SET github_login = ?, last_login_at = ?, updated_at = ? WHERE id = ? RETURNING id, github_user_id, github_login, role, status, created_at, updated_at, last_login_at
`

type RefreshLoginParams struct {
	GithubLogin string
	LastLoginAt sql.NullInt64
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) RefreshLogin(ctx context.Context, arg RefreshLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, refreshLogin,
		arg.GithubLogin,
		arg.LastLoginAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const setUserAccess = `-- name: SetUserAccess :one
UPDATE users SET role = ?, status = ?, updated_at = ? WHERE id = ? RETURNING id, github_user_id, github_login, role, status, created_at, updated_at, last_login_at
`

type SetUserAccessParams struct {
	Role      string
	Status    string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) SetUserAccess(ctx context.Context, arg SetUserAccessParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserAccess,
		arg.Role,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE author_profiles SET display_name = ?, bio_markdown = ?, website_url = ?, updated_at = ?
WHERE user_id = ? RETURNING user_id, slug, display_name, bio_markdown, avatar_url, website_url, created_at, updated_at
`

type UpdateProfileParams struct {
	DisplayName string
	BioMarkdown string
	WebsiteUrl  string
	UpdatedAt   int64
	UserID      int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (AuthorProfile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.DisplayName,
		arg.BioMarkdown,
		arg.WebsiteUrl,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i AuthorProfile
	err := row.Scan(
		&i.UserID,
		&i.Slug,
		&i.DisplayName,
		&i.BioMarkdown,
		&i.AvatarUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
